// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/addin-install" | "/dashboard" | "/download" | "/events" | "/google-slides-polling" | "/j/[eventCode]" | "/join" | "/join/[eventCode]" | "/lecturer/activities" | "/lecturer/analytics" | "/lecturer/create" | "/lecturer/dashboard" | "/lecturer/download" | "/lecturer/events" | "/lecturer/events/[eventId]" | "/lecturer/events/[eventId]/settings" | "/lecturer/integrations" | "/lecturer/interactions" | "/lecturer/login" | "/lecturer/qa" | "/lecturer/results" | "/lecturer/settings" | "/lecturer/team" | "/privacy" | "/support" | "/taskpane" | "/terms"
type AppRouteHandlerRoutes = "/api/analytics" | "/api/auth/login" | "/api/auth/register" | "/api/collaborators" | "/api/events" | "/api/events/join" | "/api/interactions" | "/api/powerpoint/poll-slide" | "/api/qa" | "/api/qa/upvote" | "/api/qrcode" | "/api/responses" | "/api/results"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/addin-install": {}
  "/api/analytics": {}
  "/api/auth/login": {}
  "/api/auth/register": {}
  "/api/collaborators": {}
  "/api/events": {}
  "/api/events/join": {}
  "/api/interactions": {}
  "/api/powerpoint/poll-slide": {}
  "/api/qa": {}
  "/api/qa/upvote": {}
  "/api/qrcode": {}
  "/api/responses": {}
  "/api/results": {}
  "/dashboard": {}
  "/download": {}
  "/events": {}
  "/google-slides-polling": {}
  "/j/[eventCode]": { "eventCode": string; }
  "/join": {}
  "/join/[eventCode]": { "eventCode": string; }
  "/lecturer/activities": {}
  "/lecturer/analytics": {}
  "/lecturer/create": {}
  "/lecturer/dashboard": {}
  "/lecturer/download": {}
  "/lecturer/events": {}
  "/lecturer/events/[eventId]": { "eventId": string; }
  "/lecturer/events/[eventId]/settings": { "eventId": string; }
  "/lecturer/integrations": {}
  "/lecturer/interactions": {}
  "/lecturer/login": {}
  "/lecturer/qa": {}
  "/lecturer/results": {}
  "/lecturer/settings": {}
  "/lecturer/team": {}
  "/privacy": {}
  "/support": {}
  "/taskpane": {}
  "/terms": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
