// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/addin-install/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/addin-install">> = Specific
  const handler = {} as typeof import("../../src/app/addin-install/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/download/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/download">> = Specific
  const handler = {} as typeof import("../../src/app/download/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/events">> = Specific
  const handler = {} as typeof import("../../src/app/events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/google-slides-polling/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/google-slides-polling">> = Specific
  const handler = {} as typeof import("../../src/app/google-slides-polling/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/j/[eventCode]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/j/[eventCode]">> = Specific
  const handler = {} as typeof import("../../src/app/j/[eventCode]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/join/[eventCode]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/join/[eventCode]">> = Specific
  const handler = {} as typeof import("../../src/app/join/[eventCode]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/join/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/join">> = Specific
  const handler = {} as typeof import("../../src/app/join/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lecturer/activities/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lecturer/activities">> = Specific
  const handler = {} as typeof import("../../src/app/lecturer/activities/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lecturer/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lecturer/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/lecturer/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lecturer/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lecturer/create">> = Specific
  const handler = {} as typeof import("../../src/app/lecturer/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lecturer/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lecturer/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/lecturer/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lecturer/download/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lecturer/download">> = Specific
  const handler = {} as typeof import("../../src/app/lecturer/download/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lecturer/events/[eventId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lecturer/events/[eventId]">> = Specific
  const handler = {} as typeof import("../../src/app/lecturer/events/[eventId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lecturer/events/[eventId]/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lecturer/events/[eventId]/settings">> = Specific
  const handler = {} as typeof import("../../src/app/lecturer/events/[eventId]/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lecturer/events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lecturer/events">> = Specific
  const handler = {} as typeof import("../../src/app/lecturer/events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lecturer/integrations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lecturer/integrations">> = Specific
  const handler = {} as typeof import("../../src/app/lecturer/integrations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lecturer/interactions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lecturer/interactions">> = Specific
  const handler = {} as typeof import("../../src/app/lecturer/interactions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lecturer/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lecturer/login">> = Specific
  const handler = {} as typeof import("../../src/app/lecturer/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lecturer/qa/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lecturer/qa">> = Specific
  const handler = {} as typeof import("../../src/app/lecturer/qa/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lecturer/results/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lecturer/results">> = Specific
  const handler = {} as typeof import("../../src/app/lecturer/results/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lecturer/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lecturer/settings">> = Specific
  const handler = {} as typeof import("../../src/app/lecturer/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lecturer/team/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lecturer/team">> = Specific
  const handler = {} as typeof import("../../src/app/lecturer/team/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../src/app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/support">> = Specific
  const handler = {} as typeof import("../../src/app/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/taskpane/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/taskpane">> = Specific
  const handler = {} as typeof import("../../src/app/taskpane/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../src/app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/analytics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/api/analytics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/collaborators/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/collaborators">> = Specific
  const handler = {} as typeof import("../../src/app/api/collaborators/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/events/join/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/events/join">> = Specific
  const handler = {} as typeof import("../../src/app/api/events/join/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/events">> = Specific
  const handler = {} as typeof import("../../src/app/api/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/interactions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/interactions">> = Specific
  const handler = {} as typeof import("../../src/app/api/interactions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/powerpoint/poll-slide/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/powerpoint/poll-slide">> = Specific
  const handler = {} as typeof import("../../src/app/api/powerpoint/poll-slide/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/qa/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/qa">> = Specific
  const handler = {} as typeof import("../../src/app/api/qa/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/qa/upvote/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/qa/upvote">> = Specific
  const handler = {} as typeof import("../../src/app/api/qa/upvote/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/qrcode/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/qrcode">> = Specific
  const handler = {} as typeof import("../../src/app/api/qrcode/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/responses/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/responses">> = Specific
  const handler = {} as typeof import("../../src/app/api/responses/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/results/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/results">> = Specific
  const handler = {} as typeof import("../../src/app/api/results/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
